config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories
  resources :transactions
  resources :users
  resources :wallets

  get '/dashboard', to: 'dashboards#index', as: :dashboard
  get '/notice', to: 'wallets#clear_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  belongs_to :user, optional: true
  has_many :transactions, dependent: :destroy

  enum transaction_type: %i[income expense]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  INCOME_TYPE = :income
  EXPENSE_TYPE = :expense

  TYPES = [INCOME_TYPE, EXPENSE_TYPE].freeze

  belongs_to :wallet
  belongs_to :category
  belongs_to :user

  enum transaction_type: TYPES
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wallets, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :transactions, dependent: :destroy

  has_many :expense_transaction_categories,
    -> { where("transactions.transaction_type = 1") },
    through: :transactions, source: :category

  has_many :income_transaction_categories,
    -> { where("transactions.transaction_type = 0") },
    through: :transactions, source: :category

  def user_categories(type: :expense)
    public_send("#{type}_transaction_categories").ids
  end

  def amount_for_categories(type: :expense)
    transactions.public_send(type).group(:category_id).sum(:amount).values
  end

  def category_title(type: :expense)
    public_send("#{type}_transaction_categories").pluck(:title)
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, :currency, presence: true

  scope :date_range, -> (start_date, end_date) { where(created_at: start_date.beginning_of_day..end_date.end_of_day) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to new_transaction_path
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to new_transaction_path
    else
      redirect_to edit_category_path(@category)
    end
  end

  def destroy
    @category.destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :image)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @wallets = Wallet.all.load_async
    @transactions = Transaction.all.load_async
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @expense_by_days = Wallet.date_range(created_at.day, Date.today).quantity
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = Transaction.all
  end

  def new
    redirect_to new_wallet_path if current_user.wallets.empty?
  end

  def create
    @transaction = Transaction.create(transaction_params)

    WalletUpdater.call(
      amount: params[:amount],
      transaction: @transaction,
      transaction_type: params[:transaction_type]
    )

    if @transaction.save
      redirect_to page_path('dashboard')
    else
      render :new
    end
  end

  def update
    @transaction.update(transaction_params)
  end

  private

  def transaction_params
    params.permit(:amount, :note, :transaction_type, :wallet_id, :category_id, :user_id)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!

  def new
    @wallet = Wallet.new
  end

  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.turbo_stream
        format.html { redirect_to dashboard_path }
      else
        format.turbo_stream
        format.html { render dashboard_path, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.turbo_stream
        format.html { redirect_to dashboard_path, notice: 'A wallet was successfully created!' }
      else
        format.turbo_stream
        format.html { render dashboard_path, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @wallet.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to dashboard_path, notice: 'A wallet was successfully deleted!' }
    end
  end

  def clear_message
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def wallet_params
    params.require(:wallet).permit(:name, :currency, :quantity).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
  NOTICE = {
    create: 'Post created successfully',
    update: 'Post updated successfully',
    delete: 'Post deleted successfully',
    error: 'Something went wrong'
  }.freeze

  def notice_stream(message:, status:)
    turbo_stream.replace 'notice', partial: 'notice', locals: { notice: NOTICE[message], status: status }
  end

  def form_wallet_stream(wallet:)
    turbo_stream.replace 'form', partial: 'form', locals: { wallet: wallet }
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

  <p>
    <strong>Image:</strong>
    <div id="category-image">
      <%= image_tag("#{category.image}") %>
    </div>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |f| %>
  <div>
    <%= f.label :title, class: 'd-block' %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image, class: 'd-block' %>
    <%= f.text_field :image %>
  </div>

  <div class='mt-3'>
    <%= f.submit 'Save', class: 'btn btn-dark' %>
    <%= link_to 'Back', :back, class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form', category: @category %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form', category: @category %>

app/views/dashboards/index.html.erb
<div class="container">
  <h2>Dashboard</h2>
  <h2>Hello there, <%= current_user.email %></h2>
  <h2>Profile</h2>

  <%= link_to 'Reports', page_path('reports') %>

  <%= link_to 'Back', home_path, class: 'btn btn-dark ml-3' %>
  <%= link_to 'Create transaction', new_transaction_path, class: 'btn btn-dark ml-3' %>
  <%= link_to 'Create wallet', new_wallet_path, class: 'btn btn-dark ml-3', data: { turbo_frame: 'new_wallet' } %>

  <%= turbo_stream_from :wallets %>

  <%= turbo_frame_tag :new_wallet %>

  <%= turbo_frame_tag :wallets do %>
    <div id="wallets-list" class='row'>
      <h1 class='my-5'>All Wallets</h1>
      <%= render @wallets %>
    </div>
  <% end %>
</div>

<div class='row'>
  <h1 class='my-5'>All Transactions</h1>
  <% @transactions.each do |transaction| %>
    <div class='col-3'>
      <%= render 'transactions/transaction', transaction: transaction %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='text-center mt-5'>
    <%= turbo_frame_tag :notice, class: 'w-full' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div>
  <h2>Dashboard</h2>
  <h2>Hi there, <%= current_user.email %></h2>
  <h2>Profile</h2>

  <%= link_to 'Reports', page_path('reports') %>

  <%= link_to 'Back', home_path, class: 'btn btn-dark ml-3' %>
  <%= link_to 'Create transaction', new_transaction_path, class: 'btn btn-dark ml-3' %>
  <%= link_to 'Create wallet', new_wallet_path, class: 'btn btn-dark ml-3' %>

  <div class='row'>
    <h1 class='my-5'>All Wallet</h1>
    <% current_user.wallets.each do |wallet| %>
      <div class='col-3'>
        <%= render 'wallets/wallet', wallet: wallet %>
      </div>
    <% end %>
  </div>

  </div>
  <div class='row'>
    <h1 class='my-5'>All Transacion</h1>
    <% Transaction.all.each do |transaction| %>
      <div class='col-3'>
        <%= render 'transactions/transaction', transaction: transaction %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div>
  <h1 class='my-4'>HOME</h1>
  <% if current_user %>
    <div class='d-flex justify-content-center'>
      <%= link_to 'Dashboard', dashboard_path, class: 'btn btn-dark mx-2' %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-dark mx-2 w-100', data: { turbo: false } %>
    </div>
  <% else %>
    <div class='d-flex justify-content-center'>
      <%= link_to 'Log in', new_user_session_path, class: 'btn btn-dark mx-2' %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-dark mx-2' %>
    </div>
  <% end %>
</div>

app/views/pages/reports.html.erb
<h3><%= link_to 'Dashboard', page_path('dashboard') %></h3>
<hr>
<div class="row">
  <div class="col-md-6">

    <div class="card">
      <div class="card-header">
        Bar Chart for Salary/Expense
      </div>
        <div class="card-body">
          <canvas id="chart-bar" width="400" height="400" data-data="<%= current_user.amount_for_categories %>" data-labels="<%= current_user.category_title %>"></canvas>
        </div>
    </div>

  </div>

  <div class="col-md-6">

    <div class="card">
      <div class="card-header">
        Pie Chart for Categories
      </div>
        <div class="card-body">
          <canvas id="chart-pie" width="400" height="400" data-data="<%#= %>"%>"></canvas>
        </div>
    </div>

  </div>
</div>

app/views/transactions/_transaction.html.erb
<p>Category: <%= transaction.category.title %></p>
<p>Type: <%= transaction.transaction_type %></p>
<p>Amount: <%= transaction.amount %></p>
<p>Note: <%= transaction.note %></p>
<hr>

app/views/transactions/index.html.erb
<h2>Transactions</h2>
<p><%= render @transactions %></p>

app/views/transactions/new.html.erb
<div class='container text-center my-5'>
  <h3>Add transaction</h3>

  <%= form_with url: transactions_path, method: :post, class: 'w-50 m-auto p-4 border border-dark', data: { turbo:false } do |f| %>
    <% if @transaction %>
      <% @transaction.errors.full_messages.each do |msg| %>
        <div class='alert alert-dark mx-auto mb-4 mt-3'>
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <div class='row justify-content-center mb-4'>
      <div class='col-5'>
        <span class='border-bottom m-auto d-block'>Wallet</span>
        <div class='d-flex border-bottom'>
          <img src='https://img.icons8.com/doodle/48/000000/wallet--v1.png'/>
          <%= f.select(:wallet_id, options_for_select(current_user.wallets.map { |wallet| [wallet.name, wallet.id] }), {}, { class: 'form-select shadow-none text-center border-0' }) %>
        </div>
      </div>

      <div class='col-5'>
        <span class='border-bottom m-auto d-block'>Amount</span>
        <div class='d-flex border-bottom'>
          <img src='https://img.icons8.com/doodle/48/000000/coins--v1.png'/>
          <%= f.number_field :amount, value: 0, class: 'form-control text-cetner border-0 text-center' %>
        </div>
      </div>
    </div>

    <%= f.label :transaction_type %>
    <%= f.select(:transaction_type, Transaction.transaction_types.keys, {}, { class: 'form-control text-center border-dark mb-4' }) %>

    <%= f.label :category %>
    <%= f.select(:category_id, options_for_select(Category.all.map { |category| [category.title, category.id] }), {}, { class: 'form-control text-center border-dark mb-4' }) %>

    <%= f.label :note %>
    <%= f.text_area :note, class: 'form-control mb-4 border-dark text-center' %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit 'Create', class: 'btn btn-dark w-50' %>
  <% end %>
</div>

app/views/wallets/_form.html.erb
<%= form_with(
      model: wallet,
      id: 'form',
      class: 'w-50 m-auto p-4 border border-dark',
      html: {
        data: { controller: 'notice', action: 'submit->notice#clear' }
      }
    ) do |f| %>
  <% if @wallet %>
    <% @wallet.errors.full_messages.each do |msg| %>
      <div class='alert alert-dark mx-auto mb-4 mt-3'>
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control mb-4 border-dark text-center' %>

  <div class='row'>
    <div class='col-md-6'>
      <%= f.label :currency %>
      <%= f.select(:currency, options_for_select([['Spanish dollar'], ['Pound sterling'], ['U.S. dollar'], ['Euro'], ['Ukrainian hryvnia']]), {}, { class: 'form-control text-center border-dark mb-4' }) %>
    </div>
    <div class='col-md-6'>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'form-control mb-4 border-dark text-center', value: 0 %>
    </div>
  </div>

  <%= f.submit 'Create', class: 'btn btn-dark w-50' %>
<% end %>

app/views/wallets/_notice.html.erb
<p class="animate-pulse opacity-80 w-full py-2 px-3 bg-<%= status %>-50 mb-5 text-<%= status %>-500 font-medium rounded-lg inline-block"
   id="notice"><%= notice %>
</p>

app/views/wallets/_wallet.html.erb
<%= turbo_frame_tag(dom_id(wallet), class: 'col-3') do %>
  <div class="card p-3">
    <p>Name: <%= wallet.name %></p>
    <p>Currency: <%= wallet.currency %></p>
    <p>Quantity: <%= wallet.quantity %></p>
  </div>
  <br>
<% end %>

app/views/wallets/clear_message.turbo_stream.erb
<%= turbo_stream.replace 'notice' do %>
  <%= turbo_frame_tag :notice %>
<% end %>

app/views/wallets/create.turbo_stream.erb
<% if @wallet.errors.present? %>
  <%= notice_stream(message: :error, status: 'red') %>
  <%= form_wallet_stream(wallet: @wallet) %>
<% else %>
  <%= notice_stream(message: :create, status: 'green') %>
  <%= turbo_stream.replace(:new_wallet) do %>
    <%= turbo_frame_tag :new_wallet %>
  <% end %>
  <%#= turbo_stream.append 'wallets-list', partial: 'wallet', locals: { wallet: @wallet } %>
  <%= Turbo::StreamsChannel.broadcast_append_to 'wallets', target: 'wallets-list', partial: 'wallets/wallet', locals: { wallet: @wallet } %>
<% end %>

app/views/wallets/destroy.turbo_stream.erb
<%= notice_stream(message: :delete, status: 'green') %>
<%= turbo_stream.remove @wallet %>

app/views/wallets/new.html.erb
<%= turbo_frame_tag dom_id @wallet do %>
  <div class='container text-center mt-5'>
    <h3>New wallet</h3>

    <%= render 'form', wallet: @wallet %>
  </div>
<% end %>

app/views/wallets/update.turbo_stream.erb
<% if @wallet.errors.present? %>
  <%= notice_stream(message: :error, status: 'red') %>
  <%= form_wallet_stream(post: @wallet) %>
<% else %>
  <%= notice_stream(message: :update, status: 'green') %>
  <%= turbo_stream.replace dom_id(@wallet), partial: 'post', locals: { post: @wallet } %>
<% end %>